set(Boost_FOUND TRUE)
set(Boost_VERSION 108400)
set(Boost_VERSION_STRING 1.84.0)
set(Boost_INCLUDE_DIRS "${CUEMOL_WASM_ROOT}/.cache/deps/boost_1_84_0")
if(NOT TARGET Boost::filesystem)
  file(GLOB _boost_fs "${Boost_INCLUDE_DIRS}/libs/filesystem/src/*.cpp")
  add_library(cuemol_boost_filesystem STATIC ${_boost_fs})
  target_include_directories(cuemol_boost_filesystem PUBLIC "${Boost_INCLUDE_DIRS}")
  target_compile_definitions(cuemol_boost_filesystem PUBLIC BOOST_ALL_NO_LIB BOOST_FILESYSTEM_NO_CXX20_ATOMIC_REF)
  add_library(Boost::filesystem ALIAS cuemol_boost_filesystem)
  foreach(_part headers system timer chrono thread)
    add_library(cuemol_boost_${_part} INTERFACE)
    target_include_directories(cuemol_boost_${_part} INTERFACE "${Boost_INCLUDE_DIRS}")
    add_library(Boost::${_part} ALIAS cuemol_boost_${_part})
  endforeach()
endif()
foreach(_part filesystem system timer chrono thread)
  string(TOUPPER "${_part}" _upper)
  set(Boost_${_upper}_FOUND TRUE)
endforeach()
